name: 'Relatório de testes'

on:
  workflow_run:
    workflows: ['Executar testes']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Resultados dos testes
          path: '**/TEST-*.xml'
          reporter: java-junit
